### ISSUE TITLE
Múltiples deshacer para los comandos?

### ISSUE THREAD

**Issue by ivanderk** [CoEValencia/codingDojo#11]
¿Los requisitos dicen algo sobre cuántos comandos se pueden deshacer? 

- ¿Uno?

- Ilimitado (poco probable ya que los rovers tienen poca memoria :-))? 

-  El historial de deshacer debe estar delimitado por un valor configurable

**Comment by pajimene** [comment]
Buena pregunta. Pues en realidad no dicen nada, pero para no complicarlo mucho serán ilimitados, confiemos que el Rover tenga suficiente memoria :p
La dificultad es ejecutar el "undo", no en ponerle un límite ;)

Y además, el "undo" se hace sobre comandos efectivos del Rover. Es decir que dos comandos "undo" seguidos no significan un "redo". Ejemplo: "FFFUU" se hace "undo" sobre los dos últimos "FF" y el resultado final sería como si solo se hubiera ejecutado "F".
